apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: tasks   
  creationTimestamp: null
  labels:
    io.kompose.service: keycloak-data
  name: keycloak-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: ""
status: {}
