FROM quay.io/keycloak/keycloak:latest as builder

ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

WORKDIR /opt/keycloak

RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:latest

COPY --from=builder /opt/keycloak /opt/keycloak/
COPY config.json /opt/keycloak/data/import/config.json

ENV KC_IMPORT=/opt/keycloak/data/import/config.json
ENV KC_ADMIN=admin
ENV KC_ADMIN_PASSWORD=admin

CMD ["start", "--import-realm"]




