name: CI/CD Multiarch

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./docker-part/frontend
          file: ./docker-part/frontend/Dockerfile.frontend
          push: true
          platforms: linux/amd64,linux/arm64
          tags: olhaya/frontend:multiarch

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./docker-part/backend/python
          file: ./docker-part/backend/python/Dockerfile.backend
          push: true
          platforms: linux/amd64,linux/arm64
          tags: olhaya/backend:multiarch

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./docker-part/backend/express
          file: ./docker-part/backend/express/Dockerfile.express
          push: true
          platforms: linux/amd64,linux/arm64
          tags: olhaya/express-backend:multiarch

      - name: Build and push keycloak image
        uses: docker/build-push-action@v5
        with:
          context: ./docker-part/keycloak
          file: ./docker-part/keycloak/Dockerfile.keycloak
          push: true
          platforms: linux/amd64,linux/arm64
          tags: olhaya/keycloak:multiarch
